# Generated by Django 4.1 on 2023-02-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='جنود',
            fields=[
                ('اسم', models.CharField(max_length=64)),
                ('رقم_عسكرى', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
