# Generated by Django 4.1 on 2023-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='جنود',
            options={'verbose_name': 'جنود'},
        ),
        migrations.AlterField(
            model_name='جنود',
            name='اسم',
            field=models.CharField(max_length=64, verbose_name='الإســـــم'),
        ),
    ]
