# Generated by Django 4.1 on 2023-02-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_جنود_options_alter_جنود_اسم'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='جنود',
            options={'verbose_name_plural': 'قوة الجنود '},
        ),
        migrations.AlterField(
            model_name='جنود',
            name='رقم_عسكرى',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='الرقم العسكرى'),
        ),
    ]
