# Generated by Django 4.1 on 2023-05-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_جنود_options_alter_جنود_رقم_عسكرى'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='جنود',
            options={'verbose_name': 'جندى', 'verbose_name_plural': 'قوة الجنود '},
        ),
    ]
