# Generated by Django 4.1 on 2023-05-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_جنود_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ضباط',
            fields=[
                ('اسم', models.CharField(max_length=64, verbose_name='الإســـــم')),
                ('رقم_الأقدمية', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='رقم الأقدمية')),
                ('صورة_شخصية', models.ImageField(default='../media/الصور الشخصية/no-profile.png', upload_to='الصور الشخصية/ضباط')),
            ],
            options={
                'verbose_name': 'ضابط',
                'verbose_name_plural': 'قوة الضباط ',
            },
        ),
        migrations.CreateModel(
            name='ضباط_صف',
            fields=[
                ('اسم', models.CharField(max_length=64, verbose_name='الإســـــم')),
                ('رقم_عسكرى', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='الرقم العسكرى')),
                ('صورة_شخصية', models.ImageField(default='../media/الصور الشخصية/no-profile.png', upload_to='الصور الشخصية/ضباط صف')),
            ],
            options={
                'verbose_name': 'ضابط صف',
                'verbose_name_plural': 'قوة ضباط الصف ',
            },
        ),
        migrations.AddField(
            model_name='جنود',
            name='صورة_شخصية',
            field=models.ImageField(default='../media/الصور الشخصية/no-profile.png', upload_to='الصور الشخصية/جنود'),
        ),
    ]
