# Generated by Django 4.1 on 2023-05-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_جنود_درجة_alter_ضباط_رتبة_alter_ضباط_صف_درجة'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='جنود',
            new_name='gnod',
        ),
    ]
