# Generated by Django 4.1 on 2023-05-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_rename_جنود_gnod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ضباط',
            new_name='dobat',
        ),
        migrations.RenameModel(
            old_name='ضباط_صف',
            new_name='dobat_saf',
        ),
    ]
